config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :authors
  resources :book_authors


  delete '/books/:book_id/authors/:author_id', to: 'books#delete_author_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :authors, through: :book_authors


  def new_author=(author)
    self.authors << author
  end

  def new_author
    nil
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(author_params)
    redirect_to @author
  end

  def edit
  end

  def update
    @author.update(author_params)
    redirect_to @author
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end



  private

  def author_params
    params.require(:author).permit(:name, :birth_year)
  end

  def find_author
    @author = Author.find(params[:id])
  end
end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController

  def create
    @book_author = BookAuthor.new(book_author_params)
    if @book_author.save
      redirect_to book_path(book_author_params[:book_id])
    end
  end

  private

  def book_author_params
    params.require(:book_author).permit(:book_id, :author_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @authors = Author.all
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to @book
  end


  def delete_author_books
    @book_author = BookAuthor.find_by(author_id: params[:author_id], book_id: params[:book_id])
    @book_author.destroy
    redirect_to Book.find(params[:book_id])
  end


  private
  def book_params
    params.require(:book).permit(:title, :pages, :book_authors)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_authors_helper.rb
module BooksAuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
<p><%= f.label :name %>
<%= f.text_field :name %></p>
<p><%= f.label :birth_year %>
<%= f.number_field :birth_year %></p>
<%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<%= render "form" %>

app/views/authors/index.html.erb
<h1>Authors!</h1>
<%= link_to "New Author", new_author_path %>
<ul>
  <% @authors.each do |author| %>
  <li><%= link_to author.name, author %> (b. <%= author.birth_year %>)</li>
<% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render "form" %>

app/views/authors/show.html.erb
<h1><%= "#{@author.name} (b. #{@author.birth_year})" %></h1>

Books:
<ul>
  <% @author.books.each do |book| %>
  <li><%= link_to book.title, book %></li>
<% end %>
</ul>


<%= link_to "Edit #{@author.name}", edit_author_path(@author) %>
<%= button_to "Delete #{@author.name}", @author, method: :delete %>

app/views/books/index.html.erb
<h1>Books!</h1>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, book %> (<%= book.pages %> pages)</li>
  <% end %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %> (<%= @book.pages %> pages)</h1>
<h2>Authors:</h2>
<ul>
  <% @book.authors.each do |author| %>
    <li>
      <%= link_to author.name, author %> (b. <%= author.birth_year %>)
      <%= button_to "Remove author", "/books/#{@book.id}/authors/#{author.id}", method: :delete %>
    </li>
  <% end %>
</ul>

<%= form_for @book.book_authors.build do |f| %>
  <%= f.label :author %>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= f.collection_select :author_id, Author.all, :id, :name %>
  <%= f.submit "Add author"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorBookRailsPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ol>
      <li><%= link_to "Authors Index", authors_path %></li>
      <li><%= link_to "Books Index", books_path %></li>
    </ol>
    <hr>
    <%= yield %>
  </body>
</html>